### PR TITLE
TextMate 2

### PR DESCRIPTION
**Pull request by philippec**
Hello,

It would be very useful to support the new TextMate 2 beta. I've been using this for a while, and it's stable for me.

It could also be removed when TM2 actually ships, although it probably won't change anything to leave it there.

Thanks!
Philippe Casgrain

### CODE REVIEW

**Comment by GreyBurkart** [comment]
One better! QuickCursor 2.6 (or commit 19b6b64bbc) adds a user-editable Bundle ID list. Sorry for not getting back to you sooner, I didn't realize this had gone unanswered!

**Comment by sorbits** [comment]
It’s certainly nice that the user can add arbitrary bundle identifiers himself, but wouldn’t it still make sense to take this pull request to improve the experience?

**Comment by jessegrosjean** [comment]
Allan,

Just added. Was avoiding because of the “preview” aspect, but it doesn’t
really matter, so just added. Unfortunately I’m not sure I’ve we’ll be able
to get this version into the app store. Currently it requires UI automation
to work (and I don’t think that I can sandbox that) and so QuickCursor is
sorta stuck. Though people can still download and build themselves. And if
I can’t find a better way I’ll probably just make a free build on my
website.

Jesse

**Comment by sorbits** [comment]
Thanks! The “preview” suffix was mainly to allow it to run side-by-side with 1.x, we’ll probably keep it for quite a while (and pile up the amount of stuff we need to change when we finally drop it)…

Btw: would be nice if you clarified the source license — I could see a generalization of QuickCursor that would allow general services to run, so we’d get a sort of TextExpander kind of program, but it would show UI for the insertion, for example one might have a key to insert a GitHub issue reference (that would open a UI for searching one’s GitHub issues), would such thing classify as “similar apps based on this code”, hence prohibit the distribution of this?

**Comment by jessegrosjean** [comment]
> Btw: would be nice if you clarified the source license — I could see a
> generalization of QuickCursor that would allow general services to run, so
> we’d get a sort of TextExpander kind of program, but it would show UI for
> the insertion, for example one might have a key to insert a GitHub issue
> reference (that would open a UI for searching one’s GitHub issues), would
> such thing classify as “similar apps based on this code”, hence prohibit
> the distribution of this?
> 
> Thanks for asking. I am just protecting myself against someone renaming the
> repository and selling in app store. I’m not sure that I fully understand
> what you are describing, but it sounds like more then just a repo rename,
> and so I think it will be OK.

Could you maybe give me a little more description. In particular do you
think this would have to be a new app, or could it just be some additional
features that are added to QuickCursor? Some of what you describe sounds a
little like OS X services, I’m wondering how this would be different.

Thanks,
Jesse

**Comment by sorbits** [comment]
Heh… I am not sure why I seem to have written off services completely. I think you’re right, what I have in mind should just be a service :)

**Pull request merged**
